kind: Service
apiVersion: v1
metadata:
  name: backend-svc
  namespace: wanderlust
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "aks-wanderlust-nodes"
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
 
