kind: Service
apiVersion: v1
metadata:
  name: frontend-svc
  namespace: wanderlust
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
