kind: Service
apiVersion: v1
metadata:
  name: frontend-svc
  namespace: wanderlust
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 80
