# kind: HorizontalPodAutoscaler
# apiVersion: autoscaling/v2
# metadata:
#   name: wanderlust-hpa
#   namespace: wanderlust
# spec:
#   scaleTargetRef: 
#     apiVersion: apps/v1
#     kind: Deployment
#     name: wander-deployment
#   minReplicas: 1
#   maxReplicas: 2
#   metrics:
#   - type: Resource
#     resource: 
#       name: cpu   
#       target:   
#         type: Utilization
#         averageUtilization: 70 
