kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 5Gi
  accessModes: 
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/db
  
